// Generated by gencpp from file myturtlebot/TurtlebotStatusRequest.msg
// DO NOT EDIT!


#ifndef MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSREQUEST_H
#define MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myturtlebot
{
template <class ContainerAllocator>
struct TurtlebotStatusRequest_
{
  typedef TurtlebotStatusRequest_<ContainerAllocator> Type;

  TurtlebotStatusRequest_()
    : forwardrqst(false)  {
    }
  TurtlebotStatusRequest_(const ContainerAllocator& _alloc)
    : forwardrqst(false)  {
  (void)_alloc;
    }



   typedef uint8_t _forwardrqst_type;
  _forwardrqst_type forwardrqst;




  typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurtlebotStatusRequest_

typedef ::myturtlebot::TurtlebotStatusRequest_<std::allocator<void> > TurtlebotStatusRequest;

typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusRequest > TurtlebotStatusRequestPtr;
typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusRequest const> TurtlebotStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myturtlebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f32fd0fb15c5c142bc743e3e76695229";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf32fd0fb15c5c142ULL;
  static const uint64_t static_value2 = 0xbc743e3e76695229ULL;
};

template<class ContainerAllocator>
struct DataType< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myturtlebot/TurtlebotStatusRequest";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool forwardrqst\n\
";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.forwardrqst);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtlebotStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myturtlebot::TurtlebotStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "forwardrqst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forwardrqst);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSREQUEST_H
