// Generated by gencpp from file myturtlebot/TurtlebotStatusResponse.msg
// DO NOT EDIT!


#ifndef MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSRESPONSE_H
#define MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myturtlebot
{
template <class ContainerAllocator>
struct TurtlebotStatusResponse_
{
  typedef TurtlebotStatusResponse_<ContainerAllocator> Type;

  TurtlebotStatusResponse_()
    : range(0.0)
    , forwardresp(false)  {
    }
  TurtlebotStatusResponse_(const ContainerAllocator& _alloc)
    : range(0.0)
    , forwardresp(false)  {
  (void)_alloc;
    }



   typedef float _range_type;
  _range_type range;

   typedef uint8_t _forwardresp_type;
  _forwardresp_type forwardresp;




  typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtlebotStatusResponse_

typedef ::myturtlebot::TurtlebotStatusResponse_<std::allocator<void> > TurtlebotStatusResponse;

typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusResponse > TurtlebotStatusResponsePtr;
typedef boost::shared_ptr< ::myturtlebot::TurtlebotStatusResponse const> TurtlebotStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myturtlebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e3cbeab986bc093e47464fdf39f6d34";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e3cbeab986bc093ULL;
  static const uint64_t static_value2 = 0xe47464fdf39f6d34ULL;
};

template<class ContainerAllocator>
struct DataType< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myturtlebot/TurtlebotStatusResponse";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 range\n\
bool forwardresp\n\
";
  }

  static const char* value(const ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range);
      stream.next(m.forwardresp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtlebotStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myturtlebot::TurtlebotStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "forwardresp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forwardresp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYTURTLEBOT_MESSAGE_TURTLEBOTSTATUSRESPONSE_H
